[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "glue"
version = "0.1.0"
description = "Advanced development infrastructure orchestration tool"
authors = [
    { name = "Matthew Messinger", email = "mattmess1221@gmail.com" },
]
dependencies = [
    "starlette>=0.46.2",
    "httpx>=0.28.1",
    "uvicorn[standard]>=0.34.2",
    "python-dotenv>=1.1.0",
    "tomli>=2.2.1; python_version < \"3.11\"",
    "psutil>=7.0.0",
    "platformdirs>=4.3.7",
    "textual>=3.1.1",
    "pywinpty>=2.0.15; os_name == \"nt\"",
]
requires-python = ">=3.9"
readme = "README.md"

[project.scripts]
glue = "glue.main:main"

[dependency-groups]
dev = [
    "mypy>=1.15.0",
    "fastapi>=0.115.12",
    "textual-dev>=1.7.0",
    "pytest>=8.3.5",
]

[tool.pdm.scripts]
typecheck = "mypy src/glue"

[[tool.hatch.envs.hatch-test.matrix]]
python = ["3.9", "3.10", "3.11", "3.12"]

[tool.ruff]
target-version = "py39"

[tool.ruff.lint]
# For rules, see https://docs.astral.sh/ruff/rules/
select = [
    "F",     # pyflakes
    "E",     # pycodestyle error
    "W",     # pycodestyle warning
    "C90",   # mccabe
    "I",     # isort
    "N",     # pep8-naming
    "D",     # pydocstyle
    "UP",    # pyupgrade
    "YTT",   # flake8-2020
    "ANN",   # flake8-annotations
    "ASYNC", # flake8-async
    "S",     # flake8-bandit
    "BLE",   # flake8-blind-except
    "FBT",   # flake8-boolean-trap
    "B",     # flake8-bugbear
    "A",     # flake8-builtins
    "DTZ",   # flake8-datetimez
    "T20",   # flake8-print
    "C4",    # flake8-comprehensions
    "FA",    # flake8-future-annotations
    "ISC",   # flake8-implicit-str-concat
    "PIE",   # flake8-pie
    "PT",    # flake8-pytest-style
    "Q",     # flake8-quotes
    "RSE",   # flake8-raise
    "RET",   # flake8-return
    "SLF",   # flake8-self
    "SIM",   # flake8-simplify
    "TID",   # flake8-tidy-imports
    "TCH",   # flake8-type-checking
    "ARG",   # flake8-unused-arguments
    "PTH",   # flake8-use-pathlib
    "ERA",   # eradicate
    "TRY",   # tryceratops
    "FLY",   # flynt
    "PERF",  # perflint
    "FURB",  # refurb
    "RUF",   # Ruff-specific rules
]
ignore = [
    "ANN1",   # missing-type-self, missing-type-cls - deprecated
    "ANN401", # any-type
    "A003",   # builtin-attribute-shadowing
    "D1",     # undocumented-public-*
    "D203",   # one-blank-line-before-class - incompatible with no-blank-line-before-class (D211)
    "D213",   # multi-line-summary-second-line - incompatible with multi-line-summary-second-line (D213)
    "ISC001", # single-line-implicit-string-concatenation - causes conflicts with ruff format
    "S101",   # assert
]

[tool.ruff.lint.extend-per-file-ignores]
"src/glue/config.py" = ["FA100"]

[tool.coverage.run]
branch = true
parallel = true

[tool.coverage.report]
skip_covered = true
show_missing = true
exclude_lines = [
    "pragma: no ?cover",
    "if .*TYPE_CHECKING:",
    "class .*\\bProtocol\\b.*:",
    "pass",
    "@overload",
]

[tool.mypy]
strict = true
warn_return_any = false

